# Generated by Django 6.0.5 on 2026-05-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragrance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
