# Generated by Django 6.0.6 on 2026-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrun',
            name='email_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default=None, max_length=10, null=True),
        ),
    ]
