# Generated by Django 6.0.6 on 2026-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0002_recommendationrun_email_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('qwen', 'Qwen')], max_length=20)),
                ('model_id', models.CharField(max_length=255)),
                ('max_tokens_default', models.PositiveIntegerField(default=1024)),
                ('supports_strict_schema', models.BooleanField(default=False)),
                ('supports_enum_enforcement', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('family', 'model_id'), name='unique_ai_model_config')],
            },
        ),
    ]
