# Generated by Django 6.0.6 on 2026-08-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0003_aimodelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrun',
            name='provider_family',
            field=models.CharField(blank=True, choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('qwen', 'Qwen')], max_length=20),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='provider_model_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
