# Generated by Django 6.0.6 on 2026-08-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0004_recommendationrun_provider_family_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aimodelconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_ai_model_config'),
        ),
    ]
