# Generated by Django 6.0.6 on 2026-08-30 22:49

from django.db import migrations

# Marker prefix used both to write and to identify the seeded row on
# reverse — lets the reverse migration distinguish "the row this migration
# created" from a same-(family, model_id) row an admin has since edited
# (whose notes would no longer start with this marker), so reversing this
# migration never deletes an admin's edits out from under them.
SEED_NOTE_MARKER = "Seeded by migration 0006_seed_default_anthropic_config"

SEED_FAMILY = "anthropic"
SEED_MODEL_ID = "claude-haiku-4-5-20251001"


def seed_default_anthropic_config(apps, schema_editor):
    """
    Seeds the pre-refactor hardcoded default (llm.py's old MODEL constant,
    confirmed via `git show main:backend/fragrance/llm.py`) as the first
    active AIModelConfig row, so a fresh environment — new clone, CI, or the
    production droplet once this branch deploys — doesn't start with zero
    rows requiring manual /admin/ setup before the pipeline can run at all.

    Guarded by "any row already exists" rather than a (family, model_id)
    lookup: dev already has a row from Task 5's manual verify_ai_model
    testing, and this must no-op there rather than either colliding with
    the unique (family, model_id) constraint (if identical) or the
    exclusivity partial unique index (if it ended up is_active=True
    alongside another active row).

    verified_at is deliberately left null — this migration never calls the
    real Anthropic API, so setting it would claim a verify_ai_model pass
    that never happened in whatever environment this runs in. Provenance
    goes in notes instead.
    """
    AIModelConfig = apps.get_model("fragrance", "AIModelConfig")
    if AIModelConfig.objects.exists():
        return
    AIModelConfig.objects.create(
        family=SEED_FAMILY,
        model_id=SEED_MODEL_ID,
        is_active=True,
        supports_strict_schema=True,
        supports_enum_enforcement=True,
        verified_at=None,
        notes=(
            f"{SEED_NOTE_MARKER}: pre-refactor hardcoded default "
            f"(family={SEED_FAMILY}, model_id={SEED_MODEL_ID}). Run "
            f"`manage.py verify_ai_model {SEED_FAMILY} {SEED_MODEL_ID}` "
            "to set verified_at for real."
        ),
    )


def remove_seeded_default_anthropic_config(apps, schema_editor):
    """
    Deletes only the specific row this migration inserted — matched on
    (family, model_id) *and* the notes marker, not (family, model_id)
    alone, since an admin could plausibly have since edited that exact row
    (including its notes) into something this migration didn't create and
    has no business deleting.
    """
    AIModelConfig = apps.get_model("fragrance", "AIModelConfig")
    AIModelConfig.objects.filter(
        family=SEED_FAMILY,
        model_id=SEED_MODEL_ID,
        notes__startswith=SEED_NOTE_MARKER,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0005_aimodelconfig_one_active_ai_model_config'),
    ]

    operations = [
        migrations.RunPython(
            seed_default_anthropic_config,
            remove_seeded_default_anthropic_config,
        ),
    ]
